/* Automatically generated by configure - do not modify */
#ifndef CONFIG_TCCDIR
# define CONFIG_TCCDIR "/usr/local/lib/tcc"
#endif
#ifndef CONFIG_TCC_PREDEFS
# define CONFIG_TCC_PREDEFS 1
#endif
#define TCC_VERSION "0.9.23"
#define GCC_MAJOR 0
#define GCC_MINOR 0
#define CC_NAME CC_gcc
#define CONFIG_TCCDIR "/usr/local/lib/tcc"
